version: '2'
volumes:
  resin-data:
services:

  queue:
    build: server
    privileged: true
    restart: always
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    volumes:
      - 'resin-data:/config'
      - 'resin-data:/logs_shared'

  websocket:
    build: server
    privileged: true
    restart: always
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    volumes:
      - 'resin-data:/config'
      - 'resin-data:/logs_shared'

  ui:
    build: client
    privileged: true
    restart: always
    ports:
      - "80:3004"
      - "81:3001"
      - "83:3003"
      - "82:3002"
      - "443:3045"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    volumes:
      - 'resin-data:/config'
      - 'resin-data:/logs_shared'

  hostname:
    image: bh.cr/g_tomas_migone1/hostname-armv7hf
    restart: no                               # Required to avoid container restarting indefinitely
    labels:
      io.balena.features.supervisor-api: 1    # Required to interact with the supervisor
    environment:
      SET_HOSTNAME: bubblesnet-controller

  wifi-connect:
    image: bh.cr/balenalabs/wifi-connect-aarch64
    restart: always
    ports:
      - "81:81"
    privileged: true
    network_mode: host

  activemq:
    image: bh.cr/gh_bubblesnet/activemq-5_17-block
    privileged: true
    restart: always
    ports:
      - "61611:61611"
      - "61612:61612"
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
      - "8162:8162"
      - "8163:8163"
      - "8164:8164"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    volumes:
      - 'resin-data:/config'
      - 'resin-data:/activemq_conf'
      - 'resin-data:/logs_shared'

  database:
    image: bh.cr/gh_bubblesnet/postgresql-11-block
    privileged: true
    restart: always
    ports:
      - "5432:5432"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    volumes:
      - 'resin-data:/postgresql_shared'
      - 'resin-data:/data'
      - 'resin-data:/logs_shared'
