#FROM balenalib/%%BALENA_MACHINE_NAME%%-node:15-buster-run
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:16.15-buster-run

# RUN apt-get update
RUN install_packages vim

COPY startservers.sh /
RUN chmod +x /startservers.sh
COPY server/src /server/src
COPY server/package.json /server
COPY server/package-lock.json /server
WORKDIR /server

RUN npm install

CMD cd /;./startservers.sh
# CMD ["bash"]
