DROP TABLE IF EXISTS usersettings;
DROP TABLE IF EXISTS strip;
DROP TABLE IF EXISTS registrationcode;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS faq;
DROP TABLE IF EXISTS currentevent;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS alertcondition;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS devicetype;
DROP TABLE IF EXISTS "user";

