# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 1-feature-firstapis, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        #          sudo bash <(curl -s https://codecov.io/bash) -t 74df7017-8e3b-462c-bb26-f99316613466 -v -s ./reports
        activemq-version: [5.16.1, 5.15.14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          sudo apt update -y -q > /dev/null 2> /dev/null
          sudo apt-get install -y -q default-jre > /dev/null 2> /dev/null
          java -version
          wget https://downloads.apache.org/activemq/${{matrix.activemq-version}}/apache-activemq-${{matrix.activemq-version}}-bin.tar.gz >/dev/null 2> /dev/null
          tar zxf apache-activemq-${{matrix.activemq-version}}-bin.tar.gz
          ls -al .
          rm ./apache-activemq-${{matrix.activemq-version}}-bin.tar.gz
          sudo ./apache-activemq-${{matrix.activemq-version}}/bin/activemq start
          npm install
          sudo npm run coverage
          sudo bash <(curl -s https://codecov.io/bash) -t 74df7017-8e3b-462c-bb26-f99316613466 -v -s ./reports
          sudo npm test
        working-directory: server
