# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 1-feature-firstapis, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#       node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          sudo apt update
          sudo apt-get install default-jre
          java -version
          sudo apt-get install activemq
          sudo find / -name activemq -print
          sudo cp activemq.service /etc/systemd/system
          sudo systemctl daemon-reload
          sudo systemctl start activemq
          sudo systemctl enable activemq
          sudo ps -ef | grep -i active
          sudo /usr/share/activemq/bin/activemq status
          npm install
          npm test
        working-directory: server
