# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 1-feature-firstapis, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#       node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          sudo apt update -y -q > /dev/null 2> /dev/null
          sudo apt-get install -y -q default-jre > /dev/null 2> /dev/null
          java -version

          sudo wget https://www-eu.apache.org/dist/activemq/5.15.8/apache-activemq-5.15.8-bin.tar.gz
          sudo tar zxf apache-activemq-5.15.8-bin.tar.gz
          sudo ln -s /opt/apache-activemq-5.15.8 activemq
          sudo rm apache-activemq-5.15.8-bin.tar.gz
          sudo cat /opt/activemq/conf/activemq.xml
          sudo /opt/activemq/bin/activemq start

          sudo netstat -antplF

          npm install
          npm test
        working-directory: server
